title: Lena Burdick # your name (or website title) here
# logo: "/images/Granada-Headshot.jpeg?raw=true" # your photo (or logo) here
logo: "https://res.cloudinary.com/dpvvvp079/image/upload/c_fill,w_300,h_300,r_max/Granada-Headshot_doho4v.jpg
" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a data-driven professional who is interested in projects that combine mathematical analysis with creative design.
  <br><br>
  Here, I hope to highlight some of my projects.  
  <br><br>
  <a href="https://www.linkedin.com/in/lena-burdick/">View My LinkedIn Profile</a> 
  <a href="https://www.upwork.com/freelancers/~01874dec4abeeccd82?mp_source=share">View My Upwork Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-E7VSJZ86MM # your Google Analytics tracking ID here
